# render.yaml (root of your repo)

services:
  # ── FastAPI API ──
  - type: web
    name: sentiment-api
    runtime: python
    branch: master
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: sentiment-redis
          property: connectionString
      - key: TWITTER_BEARER_TOKEN
        sync: false
      - key: NEWS_API_KEY
        sync: false

  # ── Celery worker ──
  - type: worker
    name: celery-worker
    runtime: python
    branch: master
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A backend.tasks.celery worker --loglevel=info
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: sentiment-redis
          property: connectionString
      - key: TWITTER_BEARER_TOKEN
        sync: false
      - key: NEWS_API_KEY
        sync: false

  # ── Redis KV store ──
  - type: redis
    name: sentiment-redis
    plan: free
    ipAllowList: []

  # ── React static site ──
  - type: web
    name: sentiment-dashboard
    runtime: static
    branch: master
    # 1) Build with the VITE_WS_URL env var present
    buildCommand: |
      # inject the API URL so import.meta.env.VITE_WS_URL is defined
      echo "VITE_WS_URL=$SERVICE_URL" >> frontend/.env
      npm install
      npm --prefix frontend run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_WS_URL
        fromService:
          type: web
          name: sentiment-api
          property: serviceUrl
