# render.yaml (at the root of your repo)
services:
  # ── FastAPI API ──
  - type: web
    name: sentiment-api
    runtime: python
    branch: master
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: sentiment-redis
          property: connectionString
      - key: TWITTER_BEARER_TOKEN
        sync: false
      - key: NEWS_API_KEY
        sync: false

  # ── Celery background worker ──
  - type: worker
    name: celery-worker
    runtime: python
    branch: master
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A backend.tasks.celery worker --loglevel=info
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: sentiment-redis
          property: connectionString
      - key: TWITTER_BEARER_TOKEN
        sync: false
      - key: NEWS_API_KEY
        sync: false

  # ── Redis KV store ──
  - type: redis
    name: sentiment-redis
    plan: free
    ipAllowList: []

  # ── React static site ──
  - type: web
    name: sentiment-dashboard
    runtime: static
    branch: master

    # 1) grab the API host:port into an env var
    envVars:
      - key: SENTIMENT_API_HOSTPORT
        fromService:
          type: web
          name: sentiment-api
          property: hostport

    # 2) build: inject VITE_WS_URL then run your normal build steps
    buildCommand: |
      # write frontend/.env so VITE_WS_URL is defined for Vite
      echo "VITE_WS_URL=http://$SENTIMENT_API_HOSTPORT" > frontend/.env
      npm install
      npm --prefix frontend run build

    staticPublishPath: frontend/dist
