services:
  # ── FastAPI API ──
  - type: web
    name: sentiment-api
    runtime: python
    branch: master
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    plan: free
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: sentiment-redis
          property: connectionString
      - key: TWITTER_BEARER_TOKEN
        sync: false
      - key: NEWS_API_KEY
        sync: false

  # ── Celery background worker ──
  - type: worker
    name: celery-worker
    runtime: python
    branch: master
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A backend.tasks.celery worker --loglevel=info
    plan: free
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: sentiment-redis
          property: connectionString
      - key: TWITTER_BEARER_TOKEN
        sync: false
      - key: NEWS_API_KEY
        sync: false

  # ── Redis (Key-Value store) ──
  - type: redis
    name: sentiment-redis
    plan: free
    ipAllowList: []  # required by Render to define visibility

  # ── React frontend ──
  - type: web
    name: sentiment-dashboard
    runtime: static
    branch: master
    buildCommand: npm install && npm --prefix frontend run build
    staticPublishPath: frontend/dist
    # ⛔ do NOT include `plan: free` here — static sites are always free
