# render.yaml
services:
  # ── FastAPI web service ──
  - type: web
    name: sentiment-api
    branch: master
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: sentiment-redis
      - key: TWITTER_BEARER_TOKEN
        sync: false
      - key: NEWS_API_KEY
        sync: false

  # ── Celery background worker ──
  - type: worker
    name: celery-worker
    branch: master
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A backend.tasks.celery worker --loglevel=info
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: sentiment-redis
      - key: TWITTER_BEARER_TOKEN
        sync: false
      - key: NEWS_API_KEY
        sync: false

  # ── React static site ──
  - type: web
    name: sentiment-dashboard
    branch: master
    runtime: static
    buildCommand: npm install && npm --prefix frontend run build
    staticPublishPath: frontend/dist

databases:
  - name: sentiment-redis
    type: redis
