services:
  # ── FastAPI API ──
  - type: web
    name: sentiment-api
    runtime: python
    branch: master
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: sentiment-redis
          property: connectionString
      - key: TWITTER_BEARER_TOKEN
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: REDDIT_CLIENT_ID
        sync: false
      - key: REDDIT_CLIENT_SECRET
        sync: false
      - key: REDDIT_USER_AGENT
        value: sentiment-app               # or sync:false if you keep it secret

  # ── Celery background worker ──
  - type: worker
    name: celery-worker
    runtime: python
    branch: master
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A backend.tasks.celery worker --loglevel=info
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: sentiment-redis
          property: connectionString
      - key: TWITTER_BEARER_TOKEN
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: REDDIT_CLIENT_ID
        sync: false
      - key: REDDIT_CLIENT_SECRET
        sync: false
      - key: REDDIT_USER_AGENT
        value: sentiment-app

  # ── Redis KV store ──
  - type: redis
    name: sentiment-redis
    plan: free
    ipAllowList: []

  # ── React static site ──
  - type: web
    name: sentiment-dashboard
    runtime: static
    branch: master

    envVars:
      - key: SENTIMENT_API_HOSTPORT
        fromService:
          type: web
          name: sentiment-api
          property: hostport

    buildCommand: |
      # ① inject websocket base URL for Vite
      echo "VITE_WS_URL=http://$SENTIMENT_API_HOSTPORT" > frontend/.env
      # ② install+build inside /frontend
      npm --prefix frontend install
      npm --prefix frontend run build          # ← fixed

    staticPublishPath: frontend/dist
